import { Router } from "express";
import { z } from "zod";
import { prisma } from "../lib/prisma.js";
import { hashPassword, verifyPassword, publicUser } from "../services/user.service.js";
import { signUser } from "../middleware/auth.js";
import { recalculateAllTimeRanks } from "../services/ranking.service.js";
const r=Router();
const registerSchema=z.object({name:z.string().min(2).max(80),email:z.string().email(),phone:z.string().min(9).max(30).optional().or(z.literal("")),password:z.string().min(6).max(200)});
r.post("/register",async(req,res,next)=>{try{const body=registerSchema.parse(req.body);const exists=await prisma.user.findUnique({where:{email:body.email.toLowerCase()}});if(exists)return res.status(409).json({message:"Bu email bilan hisob mavjud."});const passwordHash=await hashPassword(body.password);const user=await prisma.user.create({data:{name:body.name,email:body.email.toLowerCase(),phone:body.phone||null,passwordHash,online:true}});await recalculateAllTimeRanks();const dto=await publicUser(user.id);res.status(201).json({token:signUser(user),user:dto});}catch(e){next(e)}});
r.post("/login",async(req,res,next)=>{try{const email=String(req.body.email||"").toLowerCase();const user=await prisma.user.findUnique({where:{email}});if(!user||!(await verifyPassword(String(req.body.password||""),user.passwordHash)))return res.status(401).json({message:"Email yoki parol noto‘g‘ri."});const updated=await prisma.user.update({where:{id:user.id},data:{online:true}});res.json({token:signUser(updated),user:await publicUser(updated.id)});}catch(e){next(e)}});
r.post("/logout",async(req,res)=>res.json({ok:true}));
export default r;
