import "dotenv/config";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import rateLimit from "express-rate-limit";
import path from "node:path";
import fs from "node:fs";
import auth from "./routes/auth.routes.js";
import profile from "./routes/profile.routes.js";
import users from "./routes/users.routes.js";
import leaderboard from "./routes/leaderboard.routes.js";
import content from "./routes/content.routes.js";
import dashboard from "./routes/dashboard.routes.js";
import challenges from "./routes/challenge.routes.js";
import projects from "./routes/projects.routes.js";
import admin from "./routes/admin.routes.js";
import competitions from "./routes/competition.routes.js";
import company from "./routes/company.routes.js";
export const app=express();
const dirs=[path.resolve(process.env.UPLOAD_DIR||"uploads","projects"),path.resolve(process.env.UPLOAD_DIR||"uploads","avatars")];for(const d of dirs)fs.mkdirSync(d,{recursive:true});
const origins=(process.env.FRONTEND_URL||"http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001,http://localhost:3002,http://127.0.0.1:3002,http://localhost:5173").split(",").map(x=>x.trim()).filter(Boolean);
app.use(helmet({crossOriginResourcePolicy:{policy:"cross-origin"}}));
app.use(cors({origin:(o,cb)=>{if(!o)return cb(null,true);if(origins.includes(o))return cb(null,true);if(/^http:\/\/(localhost|127\.0\.0\.1|172\.\d+\.\d+\.\d+|192\.168\.\d+\.\d+)(:\d+)?$/.test(o))return cb(null,true);return cb(null,false)},credentials:true}));
app.use(express.json({limit:"2mb"}));
app.use(express.urlencoded({extended:true,limit:"2mb"}));
const limiterSafeReads=new Set(["/api/profile","/api/stats","/api/leaderboard","/api/challenges","/api/news","/api/events","/api/messages","/api/competitions"]);
app.use(rateLimit({windowMs:Number(process.env.RATE_LIMIT_WINDOW_MS||60000),max:Number(process.env.RATE_LIMIT_MAX||600),standardHeaders:"draft-8",legacyHeaders:false,skip:(req)=>req.path.startsWith("/api/leaderboard/stream")||(req.method==="GET"&&limiterSafeReads.has(req.path))||req.path.startsWith("/api/admin")||req.path.startsWith("/api/company"),message:{message:"Juda ko‘p so‘rov. Bir ozdan keyin yana urinib ko‘ring."}}));
app.use("/uploads",express.static(path.resolve(process.env.UPLOAD_DIR||"uploads"),{maxAge:"1d"}));
app.get("/",(_req,res)=>res.json({name:"DevRank UZ API",status:"ok",version:"3.0.0",time:new Date().toISOString()}));
app.get("/api/health",(_req,res)=>res.json({ok:true,service:"devrank-api",time:new Date().toISOString()}));
app.use("/api",auth,profile,users,leaderboard,content,dashboard,challenges,projects,admin,competitions,company);
app.use((req,res)=>res.status(404).json({message:"Route topilmadi.",path:req.path}));
app.use((e,_req,res,_next)=>{console.error(e);if(e?.name==="ZodError")return res.status(400).json({message:"Validatsiya xatosi",issues:e.issues});if(e?.code==="P2002")return res.status(409).json({message:"Bu qiymat allaqachon mavjud."});if(e?.code==="P2025")return res.status(404).json({message:"Ma'lumot topilmadi."});if(Number.isInteger(e?.status))return res.status(e.status).json({message:e.message});res.status(500).json({message:process.env.NODE_ENV==="production"?"Internal server error":e?.message||"Internal server error"})});
